language: node_js

node_js:
    - "0.10"
    - "0.12"
    - "node"
    - "lts/*"

before_install:
    - npm install -g grunt-cli

install:
    - npm install
    - grunt install

script:
    - grunt test:unit

services:
    - redis-server
    - mongodb
    
dist: trusty
sudo: false
